### ISSUE TITLE
Tab Temporal: malfunzionamento con Datastream e Observations

### ISSUE THREAD

**Issue by lucagiovannini** [Sandro71/SensorThingsInspector_QGIS-plugin#11]
Se creo un nuovo layer formato solo da Datastream come "Entity type" base e poi seleziono TAB Temporal: 
- non posso attivare i controlli temporalei mente invece dovrei potere
- appare il messaggio "layer without geometries" che è sbagliato, perchè il layer ha una geometria

Similmente, se creo un nuovo layer formato solo da Observations come "Entity type" basee poi seleziono TAB Temporal: 
- non posso attivare i controlli temporalei mentre invece dovrei potere

**Comment by Sandro71** [comment]
Tab abilitato anche per i layer senza geometrie

**Comment by lucagiovannini** [comment]
Verificato
