### ISSUE TITLE
Tool Inspect: limiti configurati non vengono applicati

### ISSUE THREAD

**Issue by lucagiovannini** [Sandro71/SensorThingsInspector_QGIS-plugin#12]
Verificare la corretta applicazione dei limiti.
Ad esempio, partendo da una base di features di tipo Locations e fissando il limite dei datastreams a 1 vengono invece mostrati più di un datastream.

**Comment by lucagiovannini** [comment]
I limiti su Multi/Datastreams funzionano, ma NON funzionano:

- quelli su Things (vedi primo screenshot) 

- e quelli su Observations per l'ispector di secondo livello (vedi secondo screenshot)... forse usa per sbaglio il limite settato per le observations dell'inspector di primo livello?

![image](https://github.com/user-attachments/assets/daf1158a-5b3d-4212-97de-8616634e2263)

![image](https://github.com/user-attachments/assets/23de06b7-1ae1-4f86-b242-71eadc1e1bb4)

**Comment by lucagiovannini** [comment]
Funziona, ma ne deriva una nuova richiesta:

Nel caso si parta da features di tipo FoI, l'expand procede da FoI a Observations (1:N_obs), poi M/DS (1:1), poi Things (1:1).
Quindi, di fatto, il valore limite specificato dall'utente per le Osservazioni, determina quante Things ci sono... il fatto è che spesso (come nell'esempio) quelle N Things sono in realtà la stessa. 
La richiesta quindi diventa: è possibile fare una distinct sulle Thing prima di mostrarle sull'interfaccia?
Nel casi di esempio queso farebbe sì che venisse mostrata una sola tab, con l'unica Thing veramente in gioco.

![image](https://github.com/user-attachments/assets/188919ed-b792-41f9-ae51-be7f36312ff6)

**Comment by Sandro71** [comment]
Filtrati i record Thing per l'id

**Comment by lucagiovannini** [comment]
Verificato
