### ISSUE TITLE
2dn level inspector: Date in formato MM-DD-YYYY fuorvianti

### ISSUE THREAD

**Issue by lucagiovannini** [Sandro71/SensorThingsInspector_QGIS-plugin#13]
E' possibile forzare le date in formato DD-MM-YYYY o è una impostazione di sistema?
Anche solo nel formato "Jan 01 2023" sarebbe comunque più leggibile e meno fuorviante.

![image](https://github.com/user-attachments/assets/f2570a33-86ce-4e97-8d63-54dee8d5f120)

**Comment by Sandro71** [comment]
Io lo eviterei, perché le date seguono la formattazione legata alla localizzazione (in questo caso, dire sistema americano); se imposti litaliano come lingua, vedrai anche che cambiano le regole di formattazione delle date

**Comment by lucagiovannini** [comment]
Teniamo la formattazione locale.
