### ISSUE TITLE
Problemi nell'aggiornamento dalla source sullo stesso layer

### ISSUE THREAD

**Issue by lucagiovannini** [Sandro71/SensorThingsInspector_QGIS-plugin#15]
Se creo prima un layer con solo 10 Datastreams e poi lo modifico perchè contenga solo 10 Locations:
- il tab Temporal rimane attivo -> dovrebbe diventare inattivo (Locations non ha campi temporali)
- il bottone del tool Inspect rimane disattivo -> dovrebbe attivarsi perchè Locations ha geometria
- in mappa non si caricano punti -> dovrebbero invece apparire

**Comment by lucagiovannini** [comment]
Risolti il primo e l'ultimo punto, ma rimane:
_"il bottone del tool Inspect rimane disattivo -> dovrebbe attivarsi perchè Locations ha geometria"_

**Comment by Sandro71** [comment]
Corretta attivazione \ disattivazione dei bottoni e voci del menù in base alla tipologia e alla geometria del layer attivo.

**Comment by lucagiovannini** [comment]
Verificato
