### ISSUE TITLE
ModuleNotFoundError: No module named 'SensorThingsAPI' 

### ISSUE THREAD

**Issue by claudiadragoste** [Sandro71/SensorThingsInspector_QGIS-plugin#16]
Hello,

I tried to install this new plugin and i got the error; I hve Windows 11 and I try it with QGIS 3.40.1; 
Can you help me with an advise? Thanks a lot

I paste the error I get:

Couldn't load plugin 'SensorThingsInspector_QGIS-plugin-main' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'SensorThingsAPI' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/cdragoste/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SensorThingsInspector_QGIS-plugin-main\__init__.py", line 46, in classFactory
    from SensorThingsAPI.log.logger import QgisLogger as logger
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'SensorThingsAPI'

Python version: 3.12.7 (main, Oct 25 2024, 11:18:09) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.40.1-Bratislava Bratislava, 989853a7 

Python Path:
C:/OSGeo4W/apps/qgis/./python
C:/Users/cdragoste/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/cdragoste/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:/Users/cdragoste/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\cdragoste\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\giswater
C:\Users\cdragoste\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\giswater\packages
C:\Users\cdragoste\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\giswater\core\ui\..
C:\Users/cdragoste/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\PghydroTools

**Comment by claudiadragoste** [comment]
Solved: I renamed the plugin folder: from SensorThingsInspector_QGIS-plugin-main to SensorThingsAPI

**Comment by lucagiovannini** [comment]
Hi Claudia,
glad you solved it autonomously, but the best way is to install the plugin directly from the plugin manager in QGIS:
https://plugins.qgis.org/plugins/SensorThingsAPI/
