### ISSUE TITLE
Tool Inspect: limiti configurabili

### ISSUE THREAD

**Issue by lucagiovannini** [Sandro71/SensorThingsInspector_QGIS-plugin#3]
Il tool di inspect ha alcuni parametri di configurazione che definiscono all'incirca:
- quanti dati vengono caricati al primo avvio del tool (prima cioè che l'utente abbia la possibilità di modificare la finestra temporale)
- l'ampiezza massima della finestra temporale che l'utente può richiedere

@Sandro71, ci specifichi qui quali sono questi parametri e cosa definiscono di preciso?

Stabilito questo, la richiesta è di renderli configurabili dall'utente, aggiungento una sezione specifica nel pannello del plugin.

**Comment by lucagiovannini** [comment]
Rispetto a quanto sviluppato, chiedo le seguenti modifiche:
- Rimozione delle righe: featureLimit, foiDatastreamLimit, foiObservationLimit
- Per tutte e tre le casistiche di features (Locations, FoIs, Multi/Datastreams) ci si deve riferire ai tre campi rimanenti
- I valori di default vanno impostati a: thingsLimit = 10, datastreamLimit = 10, observationLimit = 100
- "thingLimit" va rinominato in "Things" e abilitato ad essere tradotto di conseguenza
- "datastreamLimit " va rinominato in "Datastreams" e abilitato ad essere tradotto di conseguenza
- "observationLimit " va rinominato in "Observations" e abilitato ad essere tradotto di conseguenza
- Le intestazioni delle colonne "Name" e "Value" vanno rinominate in "Entity" e "Limit"

**Comment by Sandro71** [comment]
Nell'interfaccia QGIS del provider dati del SensorThings la parola Things non è tradotta: la devo comunque tradurre? Come? (Oggetto, apparecchio, ...)?

**Comment by Sandro71** [comment]
Impostato il limite delle osservazioni a 10 come default; tale valore, basso,  va bene per il reperimento dei dati delle FOI, ma nel reperimento delle osservazioni mi pare poco comodo, specie se interrogo per un periodo di date;

**Comment by lucagiovannini** [comment]
- Eliminare colonna descrizioni
- Rinominare nella colonna "Entity" la voce "Datastreams" in "Datastreams / MultiDatastreams"
- Creare due tabelline con due titoli diversi (1st level inspector, 2nd level inspector)
- La prima tabellina contiene: Things, M/DS, Obs; la seconda: Obs

**Comment by lucagiovannini** [comment]
Verificato
